# Generated by Django 2.0.6 on 2018-07-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('permissions', models.ManyToManyField(to='app01.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('server_status_id', models.IntegerField(choices=[(1, '使用中'), (2, '空闲'), (3, '租借')], default=2)),
                ('server_lease_last_day', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('server_type_id', models.IntegerField(choices=[(1, 'GPU'), (2, 'CPU')])),
                ('model_type', models.IntegerField(blank=True, choices=[(1, 'K40'), (2, 'P40'), (3, 'V100')], null=True, verbose_name='机型')),
                ('gpu_number', models.IntegerField(blank=True, null=True)),
                ('msg', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('docker_type_id', models.IntegerField(choices=[(1, '有'), (2, '没有')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('roles', models.ManyToManyField(to='app01.Role')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.User')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='service',
            field=models.ManyToManyField(to='app01.Service'),
        ),
        migrations.AddField(
            model_name='server',
            name='user_info',
            field=models.ManyToManyField(to='app01.UserInfo'),
        ),
    ]
